# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    keywords: Dachui
    backgroundpic : "img/bg.jpg"

Intro:
    name: Dachui
    slogan: "Whatever is worth doing is worth doing well <br/> Stay Hungry, Stay Foolish"
    HeadButton: Dachui

Nav:
    Home_name: Home
    is_use_categories : true 
    categories_name: categories
    is_use_archives : false
    archives_name: archives
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/julong491722262
        #500px: http://500px.com
        
    pages:
        #简历: 
        #    link: "/about/"
        #团队 :
        #    link: "/group/"
        #图库 :
        #    link: "/gallery/"
        Tags:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Artist of Programer
    description: Read the Fucking Source Code
    pic_url: /images/me.png
    goto_ulr: ""

Gallery :
    title: Mr.metro 
    description: Just another fine responsive 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: valine
    shortname: dachui 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'x8k2KxXsBheMOXhQw1qfPj6j-gzGzoHsz'
       appKey: '5Ctcw1GTFAUfF4t9I3qRLlvh'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: true
    app_id: x8k2KxXsBheMOXhQw1qfPj6j-gzGzoHsz
    app_key: 5Ctcw1GTFAUfF4t9I3qRLlvh
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML